[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
included-patches = "'Hide category bar'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Custom branding' 'Change header' 'Remove player controls background'"

[Spotify]
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts/spotify-music-and-podcasts-9-0-44-478-release/spotify-music-and-podcasts-9-0-44-478-2-android-apk-download/"
